LOCAL_PATH := $(call my-dir)


LOCAL_MODULE := myview

LOCAL_MODULE_FILENAME := libmyview

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/include

LOCAL_CFLAGS += -DHAVE_CONFIG_H -frtti -fexceptions -fopenmp -w -Ofast -DNDEBUG

LOCAL_SRC_FILES := \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_adler32.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_compress.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_crc32.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_deflate.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_infback.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_inffast.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_inflate.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_inftrees.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_trees.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_uncompr.c \
    core/src/fxcodec/fx_zlib/zlib_v128/fx_zlib_zutil.c \
    core/src/fxcodec/fx_zlib/zlib_v128/gzclose.c \
    core/src/fxcodec/fx_zlib/zlib_v128/gzlib.c \
    core/src/fxcodec/fx_zlib/zlib_v128/gzread.c \
    core/src/fxcodec/fx_zlib/zlib_v128/gzwrite.c \
    core/src/fxge/android/fpf_skiafont.cpp \
    core/src/fxge/android/fpf_skiafontmgr.cpp \
    core/src/fxge/android/fpf_skiamodule.cpp \
    core/src/fxge/android/fx_android_font.cpp \
    core/src/fxge/android/fx_android_imp.cpp \
    core/src/fpdfapi/fpdf_cmaps/fpdf_cmaps.cpp \
    core/src/fdrm/crypto/fx_crypt_aes.cpp \
    core/src/fdrm/crypto/fx_crypt.cpp \
    core/src/fdrm/crypto/fx_crypt_sha.cpp \
    core/src/fpdfapi/fpdf_edit/fpdf_edit_content.cpp \
    core/src/fpdfapi/fpdf_edit/fpdf_edit_create.cpp \
    core/src/fpdfapi/fpdf_edit/fpdf_edit_doc.cpp \
    core/src/fpdfapi/fpdf_edit/fpdf_edit_image.cpp \
    core/src/fpdfapi/fpdf_font/fpdf_font_charset.cpp \
    core/src/fpdfapi/fpdf_font/fpdf_font_cid.cpp \
    core/src/fpdfapi/fpdf_font/fpdf_font.cpp \
    core/src/fpdfapi/fpdf_font/fpdf_font_utility.cpp \
    core/src/fpdfapi/fpdf_font/ttgsubtable.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_colors.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_doc.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_func.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_graph_state.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_image.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_parser.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_parser_new.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_parser_old.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_path.cpp \
    core/src/fpdfapi/fpdf_page/fpdf_page_pattern.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_decode.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_document.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_encrypt.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_fdf.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_filters.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_objects.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_parser.cpp \
    core/src/fpdfapi/fpdf_parser/fpdf_parser_utility.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render_cache.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render_image.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render_loadimage.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render_pattern.cpp \
    core/src/fpdfapi/fpdf_render/fpdf_render_text.cpp \
    core/src/fxcodec/libjpeg/fpdfapi_jcapimin.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcapistd.c \
    core/src/fxcodec/libjpeg/fpdfapi_jccoefct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jccolor.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcdctmgr.c \
    core/src/fxcodec/libjpeg/fpdfapi_jchuff.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcinit.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcmainct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcmarker.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcmaster.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcomapi.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcparam.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcphuff.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcprepct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jcsample.c \
    core/src/fxcodec/libjpeg/fpdfapi_jctrans.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdapimin.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdapistd.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdcoefct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdcolor.c \
    core/src/fxcodec/libjpeg/fpdfapi_jddctmgr.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdhuff.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdinput.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdmainct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdmarker.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdmaster.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdmerge.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdphuff.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdpostct.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdsample.c \
    core/src/fxcodec/libjpeg/fpdfapi_jdtrans.c \
    core/src/fxcodec/libjpeg/fpdfapi_jerror.c \
    core/src/fxcodec/libjpeg/fpdfapi_jfdctfst.c \
    core/src/fxcodec/libjpeg/fpdfapi_jfdctint.c \
    core/src/fxcodec/libjpeg/fpdfapi_jidctfst.c \
    core/src/fxcodec/libjpeg/fpdfapi_jidctint.c \
    core/src/fxcodec/libjpeg/fpdfapi_jidctred.c \
    core/src/fxcodec/libjpeg/fpdfapi_jmemmgr.c \
    core/src/fxcodec/libjpeg/fpdfapi_jmemnobs.c \
    core/src/fxcodec/libjpeg/fpdfapi_jutils.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmscam02.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmscgats.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmscnvrt.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmserr.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsgamma.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsgmt.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmshalf.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsintrp.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsio0.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsio1.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmslut.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsmd5.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsmtrx.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsnamed.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsopt.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmspack.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmspcs.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsplugin.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsps2.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmssamp.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmssm.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmstypes.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsvirt.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmswtpnt.c \
    core/src/fxcodec/lcms2/lcms2-2.6/src/cmsxform.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/bio.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/cio.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/dwt.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/event.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/function_list.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/image.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/invert.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/j2k.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/jp2.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/mct.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/mqc.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/openjpeg.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/opj_clock.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/pi.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/raw.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/t1.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/t1_generate_luts.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/t2.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/tcd.c \
    core/src/fxcodec/fx_libopenjpeg/libopenjpeg20/tgt.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_bio.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_cio.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_dwt.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_event.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_function_list.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_image.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_invert.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_j2k.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_j2k_lib.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_jpt.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_mct.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_mqc.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_openjpeg.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_openjpeg_jp2.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_opj_clock.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_pi.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_raw.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_t1.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_t1_generate_luts.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_t2.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_tcd.c \
    core/src/fxcodec/fx_libopenjpeg/src/fx_tgt.c \
    core/src/fxcodec/jbig2/JBig2_ArithIntDecoder.cpp \
    core/src/fxcodec/jbig2/JBig2_GeneralDecoder.cpp \
    core/src/fxcodec/jbig2/JBig2_HuffmanDecoder.cpp \
    core/src/fxcodec/jbig2/JBig2_HuffmanTable.cpp \
    core/src/fxcodec/jbig2/JBig2_Image.cpp \
    core/src/fxcodec/jbig2/JBig2_Object.cpp \
    core/src/fxcodec/jbig2/JBig2_PatternDict.cpp \
    core/src/fxcodec/jbig2/JBig2_Segment.cpp \
    core/src/fxcodec/jbig2/JBig2_SymbolDict.cpp \
    core/src/fxcodec/jbig2/JBig2_Context.cpp \
    core/src/fxcodec/codec/fx_codec.cpp \
    core/src/fxcodec/codec/fx_codec_fax.cpp \
    core/src/fxcodec/codec/fx_codec_flate.cpp \
    core/src/fxcodec/codec/fx_codec_icc.cpp \
    core/src/fxcodec/codec/fx_codec_jbig.cpp \
    core/src/fxcodec/codec/fx_codec_jbig_enc.cpp \
    core/src/fxcodec/codec/fx_codec_jpeg.cpp \
    core/src/fxcodec/codec/fx_codec_jpx_opj.cpp \
    core/src/fpdfdoc/doc_action.cpp \
    core/src/fpdfdoc/doc_annot.cpp \
    core/src/fpdfdoc/doc_ap.cpp \
    core/src/fpdfdoc/doc_basic.cpp \
    core/src/fpdfdoc/doc_bookmark.cpp \
    core/src/fpdfdoc/doc_formcontrol.cpp \
    core/src/fpdfdoc/doc_form.cpp \
    core/src/fpdfdoc/doc_formfield.cpp \
    core/src/fpdfdoc/doc_link.cpp \
    core/src/fpdfdoc/doc_metadata.cpp \
    core/src/fpdfdoc/doc_ocg.cpp \
    core/src/fpdfdoc/doc_tagged.cpp \
    core/src/fpdfdoc/doc_utils.cpp \
    core/src/fpdfdoc/doc_viewerPreferences.cpp \
    core/src/fpdfdoc/doc_vt.cpp \
    core/src/fpdfdoc/doc_vtmodule.cpp \
    core/src/fxge/fontdata/chromefontdata/FoxitDingbats.c \
    core/src/fxge/fontdata/chromefontdata/FoxitFixedBold.c \
    core/src/fxge/fontdata/chromefontdata/FoxitFixedBoldItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitFixed.c \
    core/src/fxge/fontdata/chromefontdata/FoxitFixedItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSansBold.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSansBoldItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSans.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSansItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSansMM.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSerifBold.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSerifBoldItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSerif.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSerifItalic.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSerifMM.c \
    core/src/fxge/fontdata/chromefontdata/FoxitSymbol.c \
    core/src/fxge/fx_freetype/src/fxft_cff.c \
    core/src/fxge/fx_freetype/src/fxft_ftbase.c \
    core/src/fxge/fx_freetype/src/fxft_ftbitmap.c \
    core/src/fxge/fx_freetype/src/fxft_ftglyph.c \
    core/src/fxge/fx_freetype/src/fxft_ftinit.c \
    core/src/fxge/fx_freetype/src/fxft_ftlcdfil.c \
    core/src/fxge/fx_freetype/src/fxft_ftmm.c \
    core/src/fxge/fx_freetype/src/fxft_ftsystem.c \
    core/src/fxge/fx_freetype/src/fxft_psaux.c \
    core/src/fxge/fx_freetype/src/fxft_pshinter.c \
    core/src/fxge/fx_freetype/src/fxft_psmodule.c \
    core/src/fxge/fx_freetype/src/fxft_raster.c \
    core/src/fxge/fx_freetype/src/fxft_sfnt.c \
    core/src/fxge/fx_freetype/src/fxft_smooth.c \
    core/src/fxge/fx_freetype/src/fxft_truetype.c \
    core/src/fxge/fx_freetype/src/fxft_type1.c \
    core/src/fxge/fx_freetype/src/fxft_type1cid.c \
    core/src/fxge/dib/fx_dib_composite.cpp \
    core/src/fxge/dib/fx_dib_convert.cpp \
    core/src/fxge/dib/fx_dib_engine.cpp \
    core/src/fxge/dib/fx_dib_main.cpp \
    core/src/fxge/dib/fx_dib_transform.cpp \
    core/src/fxge/agg/agg23/fx_agg_curves.cpp \
    core/src/fxge/agg/agg23/fx_agg_driver.cpp \
    core/src/fxge/agg/agg23/fx_agg_path_storage.cpp \
    core/src/fxge/agg/agg23/fx_agg_rasterizer_scanline_aa.cpp \
    core/src/fxge/agg/agg23/fx_agg_vcgen_dash.cpp \
    core/src/fxge/agg/agg23/fx_agg_vcgen_stroke.cpp \
    core/src/fxge/ge/fx_ge.cpp \
    core/src/fxge/ge/fx_ge_device.cpp \
    core/src/fxge/ge/fx_ge_font.cpp \
    core/src/fxge/ge/fx_ge_fontmap.cpp \
    core/src/fxge/ge/fx_ge_linux.cpp \
    core/src/fxge/ge/fx_ge_path.cpp \
    core/src/fxge/ge/fx_ge_ps.cpp \
    core/src/fxge/ge/fx_ge_text.cpp \
    core/src/fxcrt/fx_arabic.cpp \
    core/src/fxcrt/fx_basic_array.cpp \
    core/src/fxcrt/fx_basic_bstring.cpp \
    core/src/fxcrt/fx_basic_buffer.cpp \
    core/src/fxcrt/fx_basic_coords.cpp \
    core/src/fxcrt/fx_basic_gcc.cpp \
    core/src/fxcrt/fx_basic_list.cpp \
    core/src/fxcrt/fx_basic_maps.cpp \
    core/src/fxcrt/fx_basic_memmgr.cpp \
    core/src/fxcrt/fx_basic_plex.cpp \
    core/src/fxcrt/fx_basic_utf.cpp \
    core/src/fxcrt/fx_basic_util.cpp \
    core/src/fxcrt/fx_basic_wstring.cpp \
    core/src/fxcrt/fxcrt_platforms.cpp \
    core/src/fxcrt/fxcrt_posix.cpp \
    core/src/fxcrt/fxcrt_windows.cpp \
    core/src/fxcrt/fx_extension.cpp \
    core/src/fxcrt/fx_ucddata.cpp \
    core/src/fxcrt/fx_unicode.cpp \
    core/src/fxcrt/fx_xml_composer.cpp \
    core/src/fxcrt/fx_xml_parser.cpp \
    core/src/fpdfapi/fpdf_basic_module.cpp \
	fpdfsdk/src/fpdf_dataavail.cpp \
	fpdfsdk/src/fpdfdoc.cpp \
	fpdfsdk/src/fpdfeditimg.cpp \
	fpdfsdk/src/fpdfeditpage.cpp \
	fpdfsdk/src/fpdf_ext.cpp \
	fpdfsdk/src/fpdf_flatten.cpp \
	fpdfsdk/src/fpdfformfill.cpp \
	fpdfsdk/src/fpdfoom.cpp \
	fpdfsdk/src/fpdfppo.cpp \
	fpdfsdk/src/fpdf_progressive.cpp \
	fpdfsdk/src/fpdfsave.cpp \
	fpdfsdk/src/fpdf_searchex.cpp \
	fpdfsdk/src/fpdf_sysfontinfo.cpp \
	fpdfsdk/src/fpdftext.cpp \
	fpdfsdk/src/fpdf_transformpage.cpp \
	fpdfsdk/src/fpdfview.cpp \
	fpdfsdk/src/fsdk_actionhandler.cpp \
	fpdfsdk/src/fsdk_annothandler.cpp \
	fpdfsdk/src/fsdk_baseannot.cpp \
	fpdfsdk/src/fsdk_baseform.cpp \
	fpdfsdk/src/fsdk_mgr.cpp \
	fpdfsdk/src/fsdk_rendercontext.cpp

LOCAL_CFLAGS += -DHAVE_CONFIG_H -w -O2 -DNDEBUG

include $(BUILD_STATIC_LIBRARY)
